global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cashcard-stream-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['source:8080', 'enricher:8080', 'sink:8080']